version: "3.7"
services:
  db:
    image: postgres:15
    container_name: db_ArcanAPI
    restart: always
    ports:
      - "1221:5432"
    env_file:
      - .env-non-dev

  redis:
    image: redis:7
    container_name: redis_ArcanAPI
    command:
      --port 5370
    expose:
      - 5370

  app:
    build:
      context: .
    env_file:
      - .env-non-dev
    container_name: arcanapi_app
#    command: bash -x "alembic upgrade head && gunicorn .src.app:app --workers 4 --worker-class uvicorn.workers.UvicornWorker --bind=0.0.0.0:8000 --reload"
    command: ["/ArcanAPI/docker/app.sh"]
    ports:
      - "9999:8000"
    depends_on:
      - db
      - redis
    restart: always