version: "3.7"
services:
  db:
    image: postgres:15
    container_name: db_ArcanAPI
    command:
      -p 1221
    expose:
      - 1221
    env_file:
      - .env-non-dev

  redis:
    image: redis:7
    container_name: redis_ArcanAPI
    command:
      --port 5370
    expose:
      - 5370

  app:
    build:
      context: .
    env_file:
      - .env-non-dev
    container_name: arcanapi_app
    command: ["/ArcanAPI/docker/app.sh"]
    ports:
      - "9999:8000"
    depends_on:
      - db
      - redis