"""add field type

Revision ID: 0c16e21f0ae1
Revises: 906232ca4224
Create Date: 2023-05-08 19:30:51.068189

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0c16e21f0ae1'
down_revision = '906232ca4224'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('arcane', sa.Column('type', sa.String(), default='minor'))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('arcane', 'type')
    # ### end Alembic commands ###
