"""initial3

Revision ID: 574d9a71fe6f
Revises: fe486c7737c3
Create Date: 2023-05-07 14:11:45.229343

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '574d9a71fe6f'
down_revision = 'fe486c7737c3'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('arcane',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('slug', sa.String(), nullable=False),
    sa.Column('card', sa.String(), nullable=False),
    sa.Column('brief', sa.ARRAY(sa.String()), nullable=True),
    sa.Column('general', sa.String(), nullable=True),
    sa.Column('personal_condition', sa.String(), nullable=True),
    sa.Column('deep', sa.String(), nullable=True),
    sa.Column('career', sa.String(), nullable=True),
    sa.Column('finances', sa.String(), nullable=True),
    sa.Column('relations', sa.String(), nullable=True),
    sa.Column('upside_down', sa.String(), nullable=True),
    sa.Column('combination', sa.String(), nullable=True),
    sa.Column('archetypal', sa.String(), nullable=True),
    sa.Column('health', sa.String(), nullable=True),
    sa.Column('remarks', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('arcane')
    # ### end Alembic commands ###
