"""initial4

Revision ID: 906232ca4224
Revises: 574d9a71fe6f
Create Date: 2023-05-08 01:32:52.914030

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '906232ca4224'
down_revision = '574d9a71fe6f'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('arcane',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('slug', sa.String(), nullable=False),
    sa.Column('card', sa.String(), nullable=False),
    sa.Column('brief', sa.String(), nullable=True),
    sa.Column('general', sa.String(), nullable=True),
    sa.Column('personal_condition', sa.String(), nullable=True),
    sa.Column('deep', sa.String(), nullable=True),
    sa.Column('career', sa.String(), nullable=True),
    sa.Column('finances', sa.String(), nullable=True),
    sa.Column('relations', sa.String(), nullable=True),
    sa.Column('upside_down', sa.String(), nullable=True),
    sa.Column('combination', sa.String(), nullable=True),
    sa.Column('archetypal', sa.String(), nullable=True),
    sa.Column('health', sa.String(), nullable=True),
    sa.Column('remarks', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('arcane')
    # ### end Alembic commands ###
